# This file was generated by GoReleaser. DO NOT EDIT.
cask "zapp" do
  version "1.5.1"

  on_macos do
    on_arm do
      sha256 "45e3470e418eb778dd356887e030ca42abc1a6aaa0dba8a602f7bbd2ff4c8794"
      url "https://github.com/ironpark/zapp/releases/download/v#{version}/zapp_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "10ccc230cdaf8e4e1531c85f7b3216a78c3fafd06cbe7c5b318c775974700e8b"
      url "https://github.com/ironpark/zapp/releases/download/v#{version}/zapp_Darwin_x86_64.tar.gz"
    end
  end

  name "zapp"
  desc "Package, sign, and notarize macOS applications"
  homepage "https://github.com/ironpark/zapp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zapp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zapp"]
    end
  end

  # No zap stanza required
end
