# This file was generated by GoReleaser. DO NOT EDIT.
cask "zapp" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "87d9f8c17e17276fb166f8d924de4bf37d00cecbb5ccfe7d0ffeb3aca77c88d2"
      url "https://github.com/ironpark/zapp/releases/download/v#{version}/zapp_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a2ea72683b465a183416bd70688acb4a1b6ecf21a36d90033fb96e913fd4b592"
      url "https://github.com/ironpark/zapp/releases/download/v#{version}/zapp_Darwin_x86_64.tar.gz"
    end
  end

  name "zapp"
  desc "Package, sign, and notarize macOS applications"
  homepage "https://github.com/ironpark/zapp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zapp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zapp"]
    end
  end

  # No zap stanza required
end
