# This file was generated by GoReleaser. DO NOT EDIT.
cask "zapp" do
  version "1.0.0-beta"

  on_macos do
    on_arm do
      sha256 "f92343c196dd9f3e9140b73b86b5ceac8dc977edea7eb2044e09ecbb176b0cf3"
      url "https://github.com/ironpark/zapp/releases/download/v#{version}/zapp_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "318f0bb2770d22c2f318019a47836a5967d68c69422261cc0effb8ff125e15eb"
      url "https://github.com/ironpark/zapp/releases/download/v#{version}/zapp_Darwin_x86_64.tar.gz"
    end
  end

  name "zapp"
  desc "Package, sign, and notarize macOS applications"
  homepage "https://github.com/ironpark/zapp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zapp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zapp"]
    end
  end

  # No zap stanza required
end
